"""Dynamic nginx reverse-proxy configuration manager.

All configuration is **derived from the service registry**
(``registry.json``).  This module never stores state itself — it reads
the registry and regenerates nginx configs every time ``sync()`` is
called.

Flow::

    API call
      → registry.put_service(...)     # write to JSON
      → nginx_manager.sync()         # read JSON → write nginx confs → reload
      → dns update                   # read JSON → RFC 2136 updates

Generated files live under ``/etc/nginx/conf.d/``:
  - ``_base.conf``        – WebSocket map, re-ddns own server blocks, fallback
  - ``<subdomain>.conf``  – one per registered service
"""

from __future__ import annotations

import logging
import subprocess
import textwrap
from pathlib import Path

from re_ddns.api import registry

logger = logging.getLogger(__name__)

NGINX_CONF_DIR = Path("/etc/nginx/conf.d")
BASE_CONF = NGINX_CONF_DIR / "_base.conf"


# ---------------------------------------------------------------------------
# Config generation
# ---------------------------------------------------------------------------

def _base_config_content() -> str:
    """Return the nginx base config (map + default fallback server)."""
    return textwrap.dedent("""\
        # Auto-generated by re_ddns – do not edit manually
        # WebSocket upgrade support
        map $http_upgrade $connection_upgrade {
            default upgrade;
            ''      close;
        }

        # ── re-ddns own UI: home.<zone> ──
        upstream _re_ddns_frontend {
            server 127.0.0.1:3000;
        }

        upstream _re_ddns_backend {
            server 127.0.0.1:8000;
        }

        server {
            listen 80;
            server_name home.reflex-ddns.com;

            location / {
                proxy_pass http://_re_ddns_frontend;
                proxy_http_version 1.1;
                proxy_set_header Host              $host;
                proxy_set_header X-Real-IP         $remote_addr;
                proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Upgrade    $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                proxy_read_timeout 86400s;
            }
        }

        server {
            listen 80;
            server_name api.reflex-ddns.com;

            location / {
                proxy_pass http://_re_ddns_backend;
                proxy_http_version 1.1;
                proxy_set_header Host              $host;
                proxy_set_header X-Real-IP         $remote_addr;
                proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Upgrade    $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                proxy_read_timeout 86400s;
            }
        }

        # ── Fallback: unknown Host → re-ddns UI ──
        server {
            listen 80 default_server;
            server_name _;

            location / {
                proxy_pass http://_re_ddns_frontend;
                proxy_http_version 1.1;
                proxy_set_header Host              $host;
                proxy_set_header X-Real-IP         $remote_addr;
                proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Upgrade    $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                proxy_read_timeout 86400s;
            }
        }
    """)


def _service_config(svc: dict) -> str:
    """Generate an nginx server block for one registry entry."""
    fqdn = f"{svc['subdomain']}.{svc['zone']}"
    upstream_name = f"_svc_{svc['subdomain']}"
    host = svc["upstream_host"]
    port = svc["frontend_port"]
    return textwrap.dedent(f"""\
        # Auto-generated by re_ddns for {fqdn}
        upstream {upstream_name} {{
            server {host}:{port};
        }}

        server {{
            listen 80;
            server_name {fqdn};

            location / {{
                proxy_pass http://{upstream_name};
                proxy_http_version 1.1;
                proxy_set_header Host              $host;
                proxy_set_header X-Real-IP         $remote_addr;
                proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Upgrade    $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                proxy_read_timeout 86400s;
            }}
        }}
    """)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def write_base_config() -> None:
    """Write the base nginx config (called once at startup)."""
    NGINX_CONF_DIR.mkdir(parents=True, exist_ok=True)
    BASE_CONF.write_text(_base_config_content())
    logger.info("Wrote base nginx config: %s", BASE_CONF)


def sync() -> bool:
    """Read the registry and regenerate **all** per-service nginx configs.

    1. Write a ``.conf`` file for every service in the registry.
    2. Remove any stale ``.conf`` files for services no longer in the registry.
    3. Reload nginx.

    Returns *True* if nginx reloaded successfully.
    """
    NGINX_CONF_DIR.mkdir(parents=True, exist_ok=True)

    services = registry.list_services()
    wanted_files: set[str] = set()

    for svc in services:
        fname = f"{svc['subdomain']}.conf"
        wanted_files.add(fname)
        conf_path = NGINX_CONF_DIR / fname
        conf_path.write_text(_service_config(svc))
        logger.info("Wrote nginx config: %s", conf_path)

    # Remove stale configs (skip _base.conf and any non-service files)
    for existing in NGINX_CONF_DIR.glob("*.conf"):
        if existing.name.startswith("_"):
            continue  # _base.conf etc.
        if existing.name not in wanted_files:
            existing.unlink()
            logger.info("Removed stale nginx config: %s", existing)

    return reload_nginx()


def reload_nginx() -> bool:
    """Test config and reload nginx.  Returns *True* on success."""
    try:
        result = subprocess.run(
            ["nginx", "-t"],
            capture_output=True, text=True, timeout=10,
        )
        if result.returncode != 0:
            logger.error("nginx config test failed:\n%s", result.stderr)
            return False

        result = subprocess.run(
            ["nginx", "-s", "reload"],
            capture_output=True, text=True, timeout=10,
        )
        if result.returncode != 0:
            logger.error("nginx reload failed:\n%s", result.stderr)
            return False

        logger.info("nginx reloaded successfully")
        return True
    except Exception as exc:
        logger.exception("Failed to reload nginx: %s", exc)
        return False
